# Page title
page_title: uStor

# Site Settings
url: "http://mymetrix.co"               # Your custom domain without trailing slash
baseurl: "/ustor_landingpage"           # Your site's subpath

# App Info
ios_app_id: 6738139909
ios_app_country: us
appstore_link: https://apps.apple.com/us/app/ustor/id6738139909
playstore_link: https://play.google.com/store/apps/details?id=com.mymetrixllc.ustor
presskit_download_link: https://mymetrix.co
app_icon: assets/ustor0.png
app_name: uStor Mobile Storage App
app_price:
app_description: Easily Organize Your Storage Spaces!
enable_smart_app_banner: true
google_analytics: G-R187ZK9TML

# Information About Yourself
your_name: MyMetrix LLC
your_link: https://mymetrix.co
your_city: Florida
email_address: support@mymetrix.co
facebook_username: https://www.facebook.com/profile.php?id=61570114654458
instagram_username: https://www.instagram.com/ustor.xyz/
twitter_username: https://x.com/ustor_xyz
github_username: garyjeppesen
youtube_username: https://www.youtube.com/@uStorStorageApp
mastodon_link: https://mastodon.social/@ustor
bluesky_link: https://bsky.app/profile/ustor.bsky.social

# Feature List
features:
  - title: Location Tracking
    description: Know exactly where everything is stored, from basement to storage unit and everywhere between.
    fontawesome_icon_name: magic

  - title: Photo Documentation
    description: Snap pictures of box contents for perfect recall without opening boxes.
    fontawesome_icon_name: mobile

  - title: Custom Categories
    description: Organize your way with personalized rooms, categories, and box types.
    fontawesome_icon_name: play-circle

  - title: Move Planning
    description: Easily track and update box locations when moving or reorganizing spaces.
    fontawesome_icon_name: sync

  - title: Content Details
    description: Add notes, descriptions, and item lists to each box for complete documentation.
    fontawesome_icon_name: adjust

  - title: Visual Organization
    description: Use custom icons and categories to make finding items intuitive and quick.
    fontawesome_icon_name: star

  - title: Quick Search
    description: Find any stored item in seconds using powerful search and filtering options.
    fontawesome_icon_name: arrow-alt-circle-down

  - title: Simple Setup
    description: Get started in minutes with an intuitive interface and guided organization process.
    fontawesome_icon_name: link

  - title: Custom Themes and Icons
    description: Pick from thousands of icons and dozens of color themes to make the app truly yours.
    fontawesome_icon_name: info-circle

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"
cover_image: assets/05.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8
device_color: black
body_background_color: "#ffffff"
link_color: "#1d63ea"
app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"
feature_title_color: "#000000"
feature_text_color: "#666666"
feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"
social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"
footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown rendering
markdown: kramdown
