#page title
page_title                                :  uStor                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6738139909                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apple-store/id6738139909?pt=127435729&ct=uStor%20Landing%20Page&mt=8     # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.mymetrixllc.ustor      # Enter Google Play Store URL.
presskit_download_link                    : https://mymetrix.co                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ustor0.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : uStor Mobile Storage App               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Easily Organize Your Storage Spaces!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

google_analytics                          : G-R187ZK9TML

# Information About Yourself
your_name                                 : MyMetrix LLC
your_link                                 : https://mymetrix.co                     
your_city                                 : Florida
email_address                             : support@mymetrix.co
facebook_username                         : https://www.facebook.com/profile.php?id=61570114654458                                          
instagram_username                        : https://www.instagram.com/ustor.xyz/
twitter_username                          : https://x.com/ustor_xyz 
github_username                           : garyjeppesen
youtube_username                          : https://www.youtube.com/@uStorStorageApp
mastodon_link                             : https://mastodon.social/@ustor
bluesky_link                              : https://bsky.app/profile/ustor.bsky.social


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Location Tracking
    description                           : Know exactly where everything is stored, from basement to storage unit and everywhere between.
    fontawesome_icon_name                 : magic
    
  - title                                 : Photo Documentation
    description                           : Snap pictures of box contents for perfect recall without opening boxes.
    fontawesome_icon_name                 : mobile

  - title                                 : Custom Categories
    description                           : Organize your way with personalized rooms, categories and box types
    fontawesome_icon_name                 : play-circle

  - title                                 : Move Planning
    description                           : Easily track and update box locations when moving or reorganizing spaces.
    fontawesome_icon_name                 : sync

  - title                                 : Content Details
    description                           : Add notes, descriptions, and item lists to each box for complete documentation.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Visual Organization
    description                           : Use cusotm icons and categories to make finding items intuitive and quick
    fontawesome_icon_name                 : star

  - title                                 : Quick Search
    description                           : Find any stored item in seconds using powerful seach and filtering options.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Simple Setup
    description                           : Get started in minutes with an intuitive interface and guided organization process.
    fontawesome_icon_name                 : link

  - title                                 : Custom Themes and Icons
    description                           : Pick from thousands of icons and dozens of color themes to make the app truly yours.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/05.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /box/:path

include:
  - _pages

url: "https://ustor.xyz"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown
